### ISSUE TITLE
libsass.dll locked by IIS Worker Process

### ISSUE THREAD

**Issue by argentini** [xoofx/SharpScss#13]
This has been an issue for a long time. It appears that invoking libsass.dll keeps it open and the file can't be overwritten during publish or rebuilding unless IIS is restarted. Can you release the DLL after each call to the SharpScss.Scss object?

**Comment by jollycic** [comment]
I have the same problem here. I guess it has to do with the `SharpScss.Scss` class being declared as `static`:  at line 17 in SharpScss/src/SharpScss/Scss.cs a comment states

> It is important to keep allocated delegate importer function, so that it will not be garbage collected
      
but since a web application never terminates unless its Application Pool is recycled, the `SharpScss.Scss` class is never garbage-collected either, so the DLL is kept locked indefinitely.

**Comment by xoofx** [comment]
> I have the same problem here. I guess it has to do with the SharpScss.Scss class being declared as static: at line 17 in SharpScss/src/SharpScss/Scss.cs a comment states

I don't think so, this delegate has nothing to do with the loaded DLL

> Can you release the DLL after each call to the SharpScss.Scss object?

Well, SharpScss is just using `DllImport` so it doesn't hold a direct reference to the DLL, that's the .NET runtime, but if IIS Worker Process cannot work with DllImport, I'm baffled. Looking on Stackoverflow, they recommend to stop and restart the app pool... so not sure I can do anything about this as this is more a .NET runtime issue than SharpScss.
